/**
 * Generates `src/generated/fixture-catalog.ts` from `reference/fixtures/`.
 *
 * The published worked examples in the guide **are** these fixture files, so
 * the converter offers the same bytes rather than a second authored copy of
 * them. Payloads are embedded as **raw text**, newline-normalised, because what
 * a reader loads into the editor must be byte-for-byte what the guide
 * publishes: re-serialising parsed JSON would silently reformat the very thing
 * the reader is being invited to edit.
 *
 * Output is git-ignored and regenerated before every typecheck, test and build,
 * so a stale catalogue cannot be committed.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const FIXTURES = fileURLToPath(new URL('../../reference/fixtures/', import.meta.url));
const OUT = fileURLToPath(new URL('../src/generated/fixture-catalog.ts', import.meta.url));

const OPENEHR_SUFFIX = '.openehr.json';
const FHIR_SUFFIX = '.fhir.json';
const PAIRING_SUFFIX = '.pairing.json';

/** Both directions, the default when no pairing marker narrows them. */
const BOTH = ['toFhir', 'toOpenehr'] as const;

interface FixtureExample {
  readonly mappingId: string;
  readonly name: string;
  readonly openehr: string;
  readonly fhir: string;
  readonly directions: readonly string[];
}

/** Read a fixture side as text, with line endings normalised and no trailing blank. */
function readSide(dir: string, stem: string, suffix: string): string {
  return readFileSync(join(dir, `${stem}${suffix}`), 'utf8')
    .replace(/\r\n/g, '\n')
    .replace(/\s+$/, '');
}

/** The directions a pairing marker claims, or both when there is no marker. */
function directionsFor(dir: string, stem: string): readonly string[] {
  const marker = join(dir, `${stem}${PAIRING_SUFFIX}`);
  if (!existsSync(marker)) return BOTH;
  const parsed = JSON.parse(readFileSync(marker, 'utf8')) as { directions?: unknown };
  if (!Array.isArray(parsed.directions)) return BOTH;
  return parsed.directions.map((direction) => String(direction));
}

export function collectFixtures(): readonly FixtureExample[] {
  const examples: FixtureExample[] = [];
  const mappingIds = readdirSync(FIXTURES, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith('_'))
    .map((entry) => entry.name)
    .sort();

  for (const mappingId of mappingIds) {
    const dir = join(FIXTURES, mappingId);
    const stems = readdirSync(dir)
      .filter((file) => file.endsWith(OPENEHR_SUFFIX))
      .map((file) => file.slice(0, -OPENEHR_SUFFIX.length))
      .sort();

    for (const stem of stems) {
      if (!existsSync(join(dir, `${stem}${FHIR_SUFFIX}`))) {
        process.stderr.write(
          `fixture-catalog: ${mappingId}/${stem} has no ${FHIR_SUFFIX} partner; skipped\n`,
        );
        continue;
      }
      examples.push({
        mappingId,
        name: stem,
        openehr: readSide(dir, stem, OPENEHR_SUFFIX),
        fhir: readSide(dir, stem, FHIR_SUFFIX),
        directions: directionsFor(dir, stem),
      });
    }
  }
  return examples;
}

function render(examples: readonly FixtureExample[]): string {
  const entries = examples
    .map(
      (example) =>
        '  {\n' +
        `    mappingId: ${JSON.stringify(example.mappingId)},\n` +
        `    name: ${JSON.stringify(example.name)},\n` +
        `    openehr: ${JSON.stringify(example.openehr)},\n` +
        `    fhir: ${JSON.stringify(example.fhir)},\n` +
        `    directions: ${JSON.stringify(example.directions)},\n` +
        '  },',
    )
    .join('\n');

  return [
    '// Generated by `npm --prefix converter-site run generate`. Do not edit.',
    '// Source: reference/fixtures/',
    '',
    "import type { Direction } from '../../../reference/src/browser/contract.ts';",
    '',
    '/** One published worked example, as the guide publishes it. */',
    'export interface FixtureExample {',
    '  readonly mappingId: string;',
    '  readonly name: string;',
    '  /** The openEHR side, verbatim. */',
    '  readonly openehr: string;',
    '  /** The FHIR side, verbatim. */',
    '  readonly fhir: string;',
    '  /** The directions the repository asserts this pair in. */',
    '  readonly directions: readonly Direction[];',
    '}',
    '',
    'export const FIXTURE_CATALOG: readonly FixtureExample[] = [',
    entries,
    '];',
    '',
  ].join('\n');
}

export function generateFixtureCatalog(): number {
  const examples = collectFixtures();
  writeFileSync(OUT, render(examples), 'utf8');
  return examples.length;
}
