/**
 * Generates `src/generated/provenance.ts`.
 *
 * Provenance is a **product feature**, not a build detail: the footer states
 * the guide version and the commit the bundle was built from, so a stale
 * deployment is visible to a reader instead of being silent. CI builds this
 * from the commit it is deploying.
 *
 * `guideBaseUrl` is the **one** place the guide's published home is named. Row
 * links in the UI are this plus the relative hrefs
 * `reference/src/publish/guide-links.ts` produces, so a preview deployment can
 * point elsewhere through `GUIDE_BASE_URL` without a code change.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { parse } from 'yaml';

const SUSHI_CONFIG = fileURLToPath(new URL('../../sushi-config.yaml', import.meta.url));
const REPO_ROOT = fileURLToPath(new URL('../../', import.meta.url));
const OUT = fileURLToPath(new URL('../src/generated/provenance.ts', import.meta.url));

/** The guide's canonical home, used unless `GUIDE_BASE_URL` overrides it. */
const DEFAULT_BASE_URL = 'http://hl7.org/fhir/uv/openehr-data-type-mapping/';

/** The `version` the IG publishes under. */
export function guideVersion(): string {
  const config = parse(readFileSync(SUSHI_CONFIG, 'utf8')) as { version?: unknown };
  return String(config.version ?? 'unknown');
}

/**
 * The short commit this bundle was built from, or the literal `unknown`.
 *
 * Never throws: a tarball with no `.git`, or a machine with no git, must still
 * produce a working bundle — one that honestly says it does not know which
 * commit it came from.
 */
export function sourceCommit(): string {
  try {
    return execFileSync('git', ['rev-parse', '--short', 'HEAD'], {
      cwd: REPO_ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    return 'unknown';
  }
}

/** Where the guide is published, with a guaranteed trailing slash. */
export function guideBaseUrl(): string {
  const configured = process.env['GUIDE_BASE_URL'];
  const base = configured === undefined || configured.trim() === '' ? DEFAULT_BASE_URL : configured.trim();
  return base.endsWith('/') ? base : `${base}/`;
}

export function generateProvenance(): void {
  const body = [
    '// Generated by `npm --prefix converter-site run generate`. Do not edit.',
    '// Sources: sushi-config.yaml, git rev-parse --short HEAD, GUIDE_BASE_URL.',
    '',
    '/** What this bundle was built from, and where the guide it links to lives. */',
    'export interface Provenance {',
    '  /** The `version` in `sushi-config.yaml`. */',
    '  readonly guideVersion: string;',
    '  /** The short commit this bundle was built from, or `unknown`. */',
    '  readonly commit: string;',
    '  /** The guide root every relative guide href is resolved against. */',
    '  readonly guideBaseUrl: string;',
    '}',
    '',
    'export const PROVENANCE: Provenance = {',
    `  guideVersion: ${JSON.stringify(guideVersion())},`,
    `  commit: ${JSON.stringify(sourceCommit())},`,
    `  guideBaseUrl: ${JSON.stringify(guideBaseUrl())},`,
    '};',
    '',
  ].join('\n');
  writeFileSync(OUT, body, 'utf8');
}
