/**
 * Managed-region parsing and splicing.
 *
 * A managed region is a byte-exact pair of HTML comments in an
 * `input/pagecontent/*.md` file:
 *
 * ```
 * <!-- >>> mapping ledger: <region-id> (generated by npm --prefix reference run render) >>> -->
 * <!-- <<< mapping ledger: <region-id> (generated by npm --prefix reference run render) <<< -->
 * ```
 *
 * The sentinels mirror the pattern `AGENTS.md` already uses for its own
 * `## GitHub Integration` block, and their normative definition lives in
 * `AGENTS.md` § *Code style*. This module reproduces them byte-for-byte and
 * never paraphrases or reformats them.
 *
 * Everything outside a sentinel pair is hand-authored prose and is **never**
 * touched by a splice.
 */

const RENDER_COMMAND = 'npm --prefix reference run render';

/** The opening sentinel for a region id, byte-exact. */
export function openerFor(id: string): string {
  return `<!-- >>> mapping ledger: ${id} (generated by ${RENDER_COMMAND}) >>> -->`;
}

/** The closing sentinel for a region id, byte-exact. */
export function closerFor(id: string): string {
  return `<!-- <<< mapping ledger: ${id} (generated by ${RENDER_COMMAND}) <<< -->`;
}

/** Matches any opener and captures its region id. */
const OPENER = /^<!-- >>> mapping ledger: (.+?) \(generated by npm --prefix reference run render\) >>> -->$/;

/** One managed region found in a document. */
export interface Region {
  readonly id: string;
  /** Offset of the first byte of the opener line. */
  readonly start: number;
  /** Offset one past the last byte of the closer line. */
  readonly end: number;
  /** The current body between the sentinels, excluding their own lines. */
  readonly body: string;
}

/**
 * Locate every managed region in a markdown document, in document order.
 *
 * @throws if an opener has no matching closer, if a closer appears with no
 * opener, or if the same region id appears twice in one document. All three are
 * unrecoverable: a half-open region would swallow prose on the next render.
 */
export function parseRegions(markdown: string): readonly Region[] {
  const regions: Region[] = [];
  const lines = markdown.split('\n');

  let offset = 0;
  let openId: string | undefined;
  let openStart = 0;
  let bodyStart = 0;
  let fence: string | undefined;

  for (const rawLine of lines) {
    const line = rawLine.endsWith('\r') ? rawLine.slice(0, -1) : rawLine;
    const lineLength = rawLine.length + 1; // include the '\n' we split on

    // A sentinel inside a fenced code block is documentation of the convention,
    // not an instance of it. `conventions.html` shows editors what a region
    // looks like, and that example must not be treated as a region.
    const fenceMatch = /^\s*(```+|~~~+)/.exec(line);
    if (fenceMatch !== null) {
      const marker = fenceMatch[1] as string;
      if (fence === undefined) fence = marker;
      else if (marker.startsWith(fence)) fence = undefined;
      offset += lineLength;
      continue;
    }
    if (fence !== undefined) {
      offset += lineLength;
      continue;
    }

    const opened = OPENER.exec(line);
    if (opened) {
      const id = opened[1] as string;
      if (openId !== undefined) {
        throw new Error(
          `managed region '${id}' opens while '${openId}' is still open — regions may not nest`,
        );
      }
      if (regions.some((r) => r.id === id)) {
        throw new Error(`managed region '${id}' appears more than once in the same page`);
      }
      openId = id;
      openStart = offset;
      bodyStart = offset + lineLength;
    } else if (openId !== undefined && line === closerFor(openId)) {
      regions.push({
        id: openId,
        start: openStart,
        end: offset + lineLength,
        body: markdown.slice(bodyStart, offset),
      });
      openId = undefined;
    } else if (line.startsWith('<!-- <<< mapping ledger: ')) {
      throw new Error(`managed region closer with no matching opener: ${line}`);
    }

    offset += lineLength;
  }

  if (openId !== undefined) {
    throw new Error(`managed region '${openId}' is opened but never closed`);
  }

  return regions;
}

/**
 * Replace the body of one region, leaving every byte outside its sentinels
 * byte-identical.
 *
 * The document's own line-ending convention is detected and preserved, so a
 * render never rewrites a CRLF file as LF (or the reverse), which would make
 * every page look changed.
 *
 * @throws if the document has no region with that id.
 */
export function spliceRegion(markdown: string, id: string, body: string): string {
  const region = parseRegions(markdown).find((r) => r.id === id);
  if (region === undefined) {
    throw new Error(`page has no managed region '${id}'`);
  }
  const eol = markdown.includes('\r\n') ? '\r\n' : '\n';
  const normalizedBody = body.replace(/\r\n/g, '\n').replace(/\n/g, eol);
  const withTrailingEol = normalizedBody.endsWith(eol)
    ? normalizedBody
    : `${normalizedBody}${eol}`;
  const replacement = `${openerFor(id)}${eol}${withTrailingEol}${closerFor(id)}${eol}`;
  return markdown.slice(0, region.start) + replacement + markdown.slice(region.end);
}

/** Every region id a document declares, in document order. */
export function regionIds(markdown: string): readonly string[] {
  return parseRegions(markdown).map((r) => r.id);
}
